spring:
  # 避免类加载器冲突，可配置参数-Dspring.devtools.restart.enabled=false
  devtools:
    restart:
      enabled: false
  # redis配置信息
  data:
    redis:
      host: localhost
      port: 6379
      password:
      ttl: 3600
  application:
    name: ai-code
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_code
    username: ${xlb.db.user}
    password: ${xlb.db.password}
  # session配置
  session:
    store-type: redis
    timeout: 2592000 # 30天过期时间

# langchain4j配置
langchain4j:
  open-ai:
    chat-model:
      api-key: ${xlb.deepseek.apikey}
      base-url: https://api.deepseek.com
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
      max-tokens: 8192
      strict-json-schema: true
      response-format: json_object # 结构化输出
      temperature: 0.0 # 代码生成类任务参数
    streaming-chat-model: # 配置SSE模式，流式输出
      base-url: https://api.deepseek.com
      api-key: ${xlb.deepseek.apikey}
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
      max-tokens: 8192
      temperature: 0.0 # 适合代码生成类任务

server:
  port: 9091
  servlet:
    context-path: /api
    # cookie 30天过期
    session:
      cookie:
        max-age: 2592000

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'ai-code-controller'
      packages-to-scan: com.xielaoban.aicode.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

mybatis-flex:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    web: info

