spring:
  application:
    name: ai-code
server:
  port: 9091
  servlet:
    context-path: /api

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'ai-code-controller'
      packages-to-scan: com.xielaoban.aicode.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn


logging:
  level:
    web: info
